# -*- coding: utf-8 -*-
"""HillClimb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ciB9FNiONICuL-J4BeENObPh0-LzF8vn
"""

import math

# Fixed points
points = [(1,5), (6,4), (5,2), (2,1)]

# Starting point
x, y = 1.0, 1.0
step = 0.1

# Objective function: total squared distance
def total_distance(x, y):
    return sum((x-px)**2 + (y-py)**2 for px, py in points)

current = total_distance(x, y)
iteration = 1

while True:
    print(f"Iteration {iteration}: ({x:.1f}, {y:.1f}) Distance = {current:.2f}")

    # Four neighbouring points
    neighbors = [
        (x + step, y),
        (x - step, y),
        (x, y + step),
        (x, y - step)
    ]

    # Find best neighbor
    best_x, best_y = x, y
    best_dist = current

    for nx, ny in neighbors:
        d = total_distance(nx, ny)
        if d < best_dist:
            best_x, best_y = nx, ny
            best_dist = d

    # Stop if no improvement
    if best_dist >= current:
        break

    # Move to the best neighbor
    x, y = best_x, best_y
    current = best_dist
    iteration += 1

print("\nOptimal Point:", (round(x, 2), round(y, 2)))
print("Minimum Distance:", round(current, 2))