# -*- coding: utf-8 -*-
"""astar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cll5CeY_rqFHVbomMIT3P12ZO5L3TBlI
"""

# pip install simpleai

# pip install pydot flask

from simpleai.search import SearchProblem, astar

GOAL = "HELLO WORLD"

class HelloProblem(SearchProblem):

    def actions(self, state):
        if len(state) < len(GOAL):
            return list(" ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        return []

    def result(self, state, action):
        return state + action

    def is_goal(self, state):
        return state == GOAL

    def heuristic(self, state):
      #count incurrent character
        wrong = sum(
            1
            for i in range(len(state))
            if state[i] != GOAL[i]
        )
        missing = len(GOAL) - len(state)
        return wrong + missing


# Create the problem
problem = HelloProblem(initial_state="")

# Solve using A* Search
result = astar(problem)

# Print the final state
print("Goal State:", result.state)

# Print the path
print("\nPath:")
for action, state in result.path():
    print(action, "->", state)

