# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LqL3JuimXC3k5FpiO_VZ9EbqUs1o-_8
"""

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    log_loss,
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)

X= np.array([[1],[2],[3],[4],[5], [6],[7],[8]])

y = np.array([0,0,0,0,1,1,1,1])

model = LogisticRegression()
model.fit(X,y)

y_pred = model.predict(X)
y_prob = model.predict_proba(X)

cost = log_loss(y,y_prob)
print("Log Loss(Cost Function):", cost)

accuracy = accuracy_score(y,y_pred)
print("Accuracy:", accuracy)

cm = confusion_matrix(y,y_pred)
print("\nConfusion Matrix:")
print(cm)

precision = precision_score(y,y_pred)
print("\nPrecision:", precision)

recall = recall_score(y,y_pred)
print("\nRecall:", recall)

f1 = f1_score(y,y_pred)
print("\nF1 Score:", f1)

hours = np.array([[6]])
prediction = model.predict(hours)
probability = model.predict_proba(hours)
print("\nFor a student who studied 6 hours:")

if prediction[0] == 1:
  print("Result: Pass")
else:
  print("Result: Fail")

print("Probability of Fail:", probability[0][0])
print("Probability of Pass:", probability[0][1])