# -*- coding: utf-8 -*-
"""CSP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6iMDnDHlE4xAaFe-uUPKqBt5XJpCkWW
"""

graph = {
    'A':['B','C'],
    'B':['A','C','D'],
    'C':['A','B','D'],
    'D':['B','C']
}

colors = ['Red','Green','Blue']

assignment = {}

def is_safe(region,color):
  for neighbor in graph[region]:
    if neighbor in assignment and assignment[neighbor] == color:
      return False
  return True

def map_coloring():
  if len(assignment)==len(graph):
    return True
  for region in graph:
    if region not in assignment:
      for color in colors:
        if is_safe(region,color):
          assignment[region]=color

          if map_coloring():
            return True

          del assignment[region]
      return False

if map_coloring():
  print("Map Coloring Solution:")
  for region in assignment:
    print(region,"->", assignment[region])
else:
  print("No Solution exists.")