# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzJ510mwvWnXPc1jMjcB0ZyEcfpeAp6G
"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

X= np.array([[1],[2],[3],[4],[5]])

y= np.array([35,40,50,55,65])

model = LinearRegression()
model.fit(X,y)

y_pred = model.predict(X)

hours = np.array([[6]])
prediction = model.predict(hours)

print("Predicted marks for 6 hours of study:", prediction[0])

print("\nLinear Regression Equation:")
print("y=", model.coef_[0],"*X+", model.intercept_)

print("\nSlope:", model.coef_[0])
print("Intercept:", model.intercept_)

mse = mean_squared_error(y,y_pred)
print("\nMean Squared Error(MSE):", mse)

mae = mean_absolute_error(y,y_pred)
print("\nMean Absolute Error(MAE):", mae)

rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)

r2 = r2_score(y,y_pred)
print("R-squared(R²):", r2)

print("\n Actual vs Predicted:")
for actual, predicted in zip(y,y_pred):
    print("Actual:", actual, "Predicted:", round(predicted,2))