# -*- coding: utf-8 -*-
"""TIC-TAE-TOE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1erNpvmjPLRFhyInoY8BbBFaNko1V4zWe
"""

board = ['' for _ in range(9)]


def display_board():
    print()
    for row in range(3):
        cells = [board[i] or str(i + 1) for i in range(row * 3, row * 3 + 3)]
        print(" " + " | ".join(cells))
        if row < 2:
            print("---+---+---")
    print()


def check_winner():
    winning_positions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]
    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] and board[a] != '':
            return board[a]
    if '' not in board:
        return 'Draw'
    return None


def minimax(is_maximizing):
    result = check_winner()
    if result == 'O':
        return 1
    if result == 'X':
        return -1
    if result == 'Draw':
        return 0

    if is_maximizing:
        best_score = -999
        for i in range(9):
            if board[i] == '':
                board[i] = 'O'
                score = minimax(False)
                board[i] = ''
                best_score = max(best_score, score)
        return best_score
    else:
        best_score = 999
        for i in range(9):
            if board[i] == '':
                board[i] = 'X'
                score = minimax(True)
                board[i] = ''
                best_score = min(best_score, score)
        return best_score


def best_move():
    if check_winner() is not None:
        return -1
    best_score = -999
    move = -1
    for i in range(9):
        if board[i] == '':
            board[i] = 'O'
            score = minimax(False)
            board[i] = ''
            if score > best_score:
                best_score = score
                move = i
    return move


def play_game():
    board[:] = ['' for _ in range(9)]
    print("TIC-TAC-TOE")
    print("You are X")
    print("Computer is O")
    result = None

    while result is None:
        display_board()
        try:
            position = int(input("Enter a position from 1-9: ")) - 1
        except ValueError:
            print("Invalid input. Enter a number from 1-9.")
            continue

        if position < 0 or position > 8 or board[position] != '':
            print("Invalid move. Try again.")
            continue

        board[position] = 'X'
        result = check_winner()
        if result is not None:
            break

        move = best_move()
        board[move] = 'O'
        print("Computer chooses:", move + 1)
        result = check_winner()

    display_board()
    if result == 'Draw':
        print("It's a draw!")
    else:
        print(result + " wins!")


if __name__ == '__main__':
    play_game()
